version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 750
  method-complexity:
    enabled: true
    config:
      threshold: 6
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 50
  nested-control-flow:
    enabled: true
    config:
      threshold: 6
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 100
  identical-code:
    enabled: true
    config:
      threshold: 100
prepare:
  fetch:
    - url: "https://raw.githubusercontent.com/fs-webdev/eslint-config-frontier/master/index.js"
      path: "eslint-config-frontier.js"
    - url: "https://raw.githubusercontent.com/fs-webdev/eslint-config-tree/master/index.js"
      path: "eslint-config-tree.js"
plugins:
  babel-eslint:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .codeclimate.eslintrc.js
      extensions:
        - .html
        - .js
      ignore_warnings: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - ToDo
      - Todo
      - TO-DO
      - To-Do
      - HACK
      - Hack
      - HERE BE DRAGONS
      - Here Be Dragons
  grep:
    enabled: true
    config:
      patterns:
        bad-merge:
          pattern: <<<<<<<|=======|>>>>>>>
          annotation: "Bad merge"
          severity: critical
          categories: ["Bug Risk", "Performance"]
          content: >
            Bad merge detected by one or more of the following strings of the form: "<<<<<<< Updated upstream", "=======", ">>>>>>> Stashed changes". In all likelihood, this will result in syntax errors when attempting to run your application.
  markdownlint:
    enabled: true
    checks:
      MD008:
        enabled: false
      MD013:
        enabled: false
      MD014:
        enabled: false
      MD015:
        enabled: false
      MD016:
        enabled: false
      MD017:
        enabled: false
      MD023:
        enabled: false
      MD024:
        enabled: false
      MD026:
        enabled: false
      MD029:
        enabled: false
      MD033:
        enabled: false
      MD034:
        enabled: false
      MD036:
        enabled: false
  shellcheck:
    enabled: true
exclude_patterns:
  - ".*"
  - bower_components/
  - build/
  - dist/
  - eslint-config-frontier.js
  - eslint-config-tree.js
  - node_modules/
  - src/
  - "**/*-polyfill.js"
  - "**/*min.*"
  - "**/reports/**/*"
  - "**/test/**/*"
  - "**/vendor/**/*"
